# Fonte
font_family      family="JetBrainsMono Nerd Font Mono" style="Bold"
font_size        13.0

# Janela
window_padding_width    10
confirm_os_window_close 0

# Transparência / blur
background_opacity         0.9
dynamic_background_opacity yes
background_blur             20

# Cursor
cursor_shape          beam
cursor_blink_interval  0.5

# Scrollback
scrollback_lines 10000

# Bordas dos painéis (splits)
window_border_width   1
active_border_color   #86aaec
inactive_border_color #1c1e27

# Barra de abas
tab_bar_style            powerline
tab_powerline_style      slanted
active_tab_foreground    #0d0f18
active_tab_background    #86aaec
inactive_tab_foreground  #a5b6cf
inactive_tab_background  #151720

# Sino
enable_audio_bell no

# Tema de cores (paleta Ayu Dark, compartilhada com o Alacritty)
include kittytheme.conf
